# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(520, 780)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(520, 780))
        mainWindow.setMaximumSize(QtCore.QSize(520, 780))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        mainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/ocm_icon_bl.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 521, 761))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 780))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.Dados = QtWidgets.QWidget()
        self.Dados.setObjectName("Dados")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.Dados)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(350, 360, 31, 156))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_4.setStyleSheet("border-image: url(:/equations/equations/theta.png);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_9.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_5.setStyleSheet("border-image: url(:/equations/equations/gamma.png);")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_9.addWidget(self.label_5)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label.setMinimumSize(QtCore.QSize(0, 60))
        self.label.setStyleSheet("image: url(:/equations/equations/r2_36.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_9.addWidget(self.label)
        self.mostrar_theta = QtWidgets.QTextBrowser(self.Dados)
        self.mostrar_theta.setGeometry(QtCore.QRect(400, 360, 91, 41))
        self.mostrar_theta.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mostrar_theta.setObjectName("mostrar_theta")
        self.mostrar_gamma = QtWidgets.QTextBrowser(self.Dados)
        self.mostrar_gamma.setGeometry(QtCore.QRect(400, 420, 91, 41))
        self.mostrar_gamma.setObjectName("mostrar_gamma")
        self.label_2 = QtWidgets.QLabel(self.Dados)
        self.label_2.setGeometry(QtCore.QRect(30, 380, 301, 71))
        self.label_2.setStyleSheet("border-image: url(:/equations/equations/weibull.png);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Dados)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 461, 270))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(9)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_22 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_22.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_12.addWidget(self.label_22)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit.setFrame(True)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_12.addWidget(self.lineEdit)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_23 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_18.addWidget(self.label_23)
        self.ttf1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.ttf1.setMinimumSize(QtCore.QSize(0, 30))
        self.ttf1.setAlignment(QtCore.Qt.AlignCenter)
        self.ttf1.setClearButtonEnabled(True)
        self.ttf1.setObjectName("ttf1")
        self.horizontalLayout_18.addWidget(self.ttf1)
        self.verticalLayout_13.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_24 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_19.addWidget(self.label_24)
        self.ttf2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.ttf2.setMinimumSize(QtCore.QSize(0, 30))
        self.ttf2.setAlignment(QtCore.Qt.AlignCenter)
        self.ttf2.setClearButtonEnabled(True)
        self.ttf2.setObjectName("ttf2")
        self.horizontalLayout_19.addWidget(self.ttf2)
        self.verticalLayout_13.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_25 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_20.addWidget(self.label_25)
        self.ttf3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.ttf3.setMinimumSize(QtCore.QSize(0, 30))
        self.ttf3.setAlignment(QtCore.Qt.AlignCenter)
        self.ttf3.setClearButtonEnabled(True)
        self.ttf3.setObjectName("ttf3")
        self.horizontalLayout_20.addWidget(self.ttf3)
        self.verticalLayout_13.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_26 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_21.addWidget(self.label_26)
        self.ttf4 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.ttf4.setMinimumSize(QtCore.QSize(30, 30))
        self.ttf4.setAlignment(QtCore.Qt.AlignCenter)
        self.ttf4.setClearButtonEnabled(True)
        self.ttf4.setObjectName("ttf4")
        self.horizontalLayout_21.addWidget(self.ttf4)
        self.verticalLayout_13.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_27 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_22.addWidget(self.label_27)
        self.ttf5 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.ttf5.setMinimumSize(QtCore.QSize(0, 30))
        self.ttf5.setAlignment(QtCore.Qt.AlignCenter)
        self.ttf5.setClearButtonEnabled(True)
        self.ttf5.setObjectName("ttf5")
        self.horizontalLayout_22.addWidget(self.ttf5)
        self.verticalLayout_13.addLayout(self.horizontalLayout_22)
        self.verticalLayout_13.setStretch(1, 186)
        self.verticalLayout_12.addLayout(self.verticalLayout_13)
        self.horizontalLayout_3.addLayout(self.verticalLayout_12)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem1 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem1)
        self.processar_rede_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.processar_rede_2.setMinimumSize(QtCore.QSize(158, 0))
        self.processar_rede_2.setObjectName("processar_rede_2")
        self.verticalLayout_8.addWidget(self.processar_rede_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem2)
        self.salvar_dados_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.salvar_dados_2.setObjectName("salvar_dados_2")
        self.verticalLayout_8.addWidget(self.salvar_dados_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem3)
        self.carregar_dados_salvos_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.carregar_dados_salvos_2.setObjectName("carregar_dados_salvos_2")
        self.verticalLayout_8.addWidget(self.carregar_dados_salvos_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.label_17 = QtWidgets.QLabel(self.Dados)
        self.label_17.setGeometry(QtCore.QRect(20, 550, 311, 81))
        self.label_17.setStyleSheet("border-image: url(:/equations/equations/lognormal_36.png);")
        self.label_17.setObjectName("label_17")
        self.verticalLayoutWidget_14 = QtWidgets.QWidget(self.Dados)
        self.verticalLayoutWidget_14.setGeometry(QtCore.QRect(350, 550, 31, 156))
        self.verticalLayoutWidget_14.setObjectName("verticalLayoutWidget_14")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_14)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_48 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.label_48.setStyleSheet("border-image: url(:/equations/equations/mu_36.png);")
        self.label_48.setObjectName("label_48")
        self.verticalLayout_21.addWidget(self.label_48)
        self.label_49 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.label_49.setStyleSheet("border-image: url(:/equations/equations/sigma_36.png);")
        self.label_49.setObjectName("label_49")
        self.verticalLayout_21.addWidget(self.label_49)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.label_3.setMinimumSize(QtCore.QSize(0, 60))
        self.label_3.setStyleSheet("image: url(:/equations/equations/r2_36.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_21.addWidget(self.label_3)
        self.mostrar_mu = QtWidgets.QTextBrowser(self.Dados)
        self.mostrar_mu.setGeometry(QtCore.QRect(400, 550, 91, 41))
        self.mostrar_mu.setObjectName("mostrar_mu")
        self.mostrar_sigma = QtWidgets.QTextBrowser(self.Dados)
        self.mostrar_sigma.setGeometry(QtCore.QRect(400, 610, 91, 41))
        self.mostrar_sigma.setObjectName("mostrar_sigma")
        self.select_weibull = QtWidgets.QRadioButton(self.Dados)
        self.select_weibull.setGeometry(QtCore.QRect(20, 340, 119, 23))
        self.select_weibull.setChecked(True)
        self.select_weibull.setObjectName("select_weibull")
        self.select_lognormal = QtWidgets.QRadioButton(self.Dados)
        self.select_lognormal.setGeometry(QtCore.QRect(20, 520, 119, 23))
        self.select_lognormal.setObjectName("select_lognormal")
        self.mostrar_r_weibull = QtWidgets.QTextBrowser(self.Dados)
        self.mostrar_r_weibull.setGeometry(QtCore.QRect(400, 480, 91, 41))
        self.mostrar_r_weibull.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mostrar_r_weibull.setObjectName("mostrar_r_weibull")
        self.mostrar_r_lognormal = QtWidgets.QTextBrowser(self.Dados)
        self.mostrar_r_lognormal.setGeometry(QtCore.QRect(400, 670, 91, 41))
        self.mostrar_r_lognormal.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mostrar_r_lognormal.setObjectName("mostrar_r_lognormal")
        self.tabWidget.addTab(self.Dados, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(0, 60, 511, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(0, 380, 511, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(20, 140, 481, 201))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_10.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(10)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(60)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.tempo_2_conf = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.tempo_2_conf.sizePolicy().hasHeightForWidth())
        self.tempo_2_conf.setSizePolicy(sizePolicy)
        self.tempo_2_conf.setMinimumSize(QtCore.QSize(80, 0))
        self.tempo_2_conf.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.tempo_2_conf.setFont(font)
        self.tempo_2_conf.setText("")
        self.tempo_2_conf.setAlignment(QtCore.Qt.AlignCenter)
        self.tempo_2_conf.setClearButtonEnabled(True)
        self.tempo_2_conf.setObjectName("tempo_2_conf")
        self.horizontalLayout_4.addWidget(self.tempo_2_conf)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(110)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(110, 0))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.exibir_conf_para_tempo = QtWidgets.QTextBrowser(self.verticalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(140)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exibir_conf_para_tempo.sizePolicy().hasHeightForWidth())
        self.exibir_conf_para_tempo.setSizePolicy(sizePolicy)
        self.exibir_conf_para_tempo.setMaximumSize(QtCore.QSize(140, 30))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.exibir_conf_para_tempo.setFont(font)
        self.exibir_conf_para_tempo.setObjectName("exibir_conf_para_tempo")
        self.horizontalLayout_4.addWidget(self.exibir_conf_para_tempo)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout_10.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.calcular_conf_para_tempo = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.calcular_conf_para_tempo.setObjectName("calcular_conf_para_tempo")
        self.horizontalLayout_6.addWidget(self.calcular_conf_para_tempo)
        spacerItem7 = QtWidgets.QSpacerItem(35, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.verticalLayout_10.addLayout(self.horizontalLayout_6)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(110)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_7.addWidget(self.label_13)
        self.conf_2_tempo = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.conf_2_tempo.sizePolicy().hasHeightForWidth())
        self.conf_2_tempo.setSizePolicy(sizePolicy)
        self.conf_2_tempo.setMinimumSize(QtCore.QSize(80, 0))
        self.conf_2_tempo.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.conf_2_tempo.setFont(font)
        self.conf_2_tempo.setText("")
        self.conf_2_tempo.setAlignment(QtCore.Qt.AlignCenter)
        self.conf_2_tempo.setClearButtonEnabled(True)
        self.conf_2_tempo.setObjectName("conf_2_tempo")
        self.horizontalLayout_7.addWidget(self.conf_2_tempo)
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(60)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_7.addWidget(self.label_14)
        self.exibir_tempo_para_conf = QtWidgets.QTextBrowser(self.verticalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(140)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exibir_tempo_para_conf.sizePolicy().hasHeightForWidth())
        self.exibir_tempo_para_conf.setSizePolicy(sizePolicy)
        self.exibir_tempo_para_conf.setMaximumSize(QtCore.QSize(140, 30))
        self.exibir_tempo_para_conf.setObjectName("exibir_tempo_para_conf")
        self.horizontalLayout_7.addWidget(self.exibir_tempo_para_conf)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem9)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem10)
        self.calcular_tempo_p_conf = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.calcular_tempo_p_conf.setObjectName("calcular_tempo_p_conf")
        self.horizontalLayout_8.addWidget(self.calcular_tempo_p_conf)
        spacerItem11 = QtWidgets.QSpacerItem(35, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem11)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(20, 460, 481, 201))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(60)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.tempo_2_falha = QtWidgets.QLineEdit(self.verticalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tempo_2_falha.sizePolicy().hasHeightForWidth())
        self.tempo_2_falha.setSizePolicy(sizePolicy)
        self.tempo_2_falha.setMinimumSize(QtCore.QSize(80, 0))
        self.tempo_2_falha.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.tempo_2_falha.setFont(font)
        self.tempo_2_falha.setText("")
        self.tempo_2_falha.setAlignment(QtCore.Qt.AlignCenter)
        self.tempo_2_falha.setClearButtonEnabled(True)
        self.tempo_2_falha.setObjectName("tempo_2_falha")
        self.horizontalLayout_9.addWidget(self.tempo_2_falha)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_9.addWidget(self.label_12)
        self.exibir_falha_para_tempo = QtWidgets.QTextBrowser(self.verticalLayoutWidget_8)
        self.exibir_falha_para_tempo.setMinimumSize(QtCore.QSize(140, 0))
        self.exibir_falha_para_tempo.setMaximumSize(QtCore.QSize(140, 30))
        self.exibir_falha_para_tempo.setObjectName("exibir_falha_para_tempo")
        self.horizontalLayout_9.addWidget(self.exibir_falha_para_tempo)
        spacerItem12 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem12)
        self.verticalLayout_11.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem13)
        self.calcular_falha_p_tempo = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        self.calcular_falha_p_tempo.setObjectName("calcular_falha_p_tempo")
        self.horizontalLayout_10.addWidget(self.calcular_falha_p_tempo)
        spacerItem14 = QtWidgets.QSpacerItem(35, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem14)
        self.verticalLayout_11.addLayout(self.horizontalLayout_10)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem15)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_11.addWidget(self.label_15)
        self.falha_2_tempo = QtWidgets.QLineEdit(self.verticalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.falha_2_tempo.sizePolicy().hasHeightForWidth())
        self.falha_2_tempo.setSizePolicy(sizePolicy)
        self.falha_2_tempo.setMinimumSize(QtCore.QSize(80, 0))
        self.falha_2_tempo.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.falha_2_tempo.setFont(font)
        self.falha_2_tempo.setText("")
        self.falha_2_tempo.setAlignment(QtCore.Qt.AlignCenter)
        self.falha_2_tempo.setClearButtonEnabled(True)
        self.falha_2_tempo.setObjectName("falha_2_tempo")
        self.horizontalLayout_11.addWidget(self.falha_2_tempo)
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_11.addWidget(self.label_16)
        self.exibir_tempo_p_falha = QtWidgets.QTextBrowser(self.verticalLayoutWidget_8)
        self.exibir_tempo_p_falha.setMinimumSize(QtCore.QSize(140, 0))
        self.exibir_tempo_p_falha.setMaximumSize(QtCore.QSize(140, 30))
        self.exibir_tempo_p_falha.setObjectName("exibir_tempo_p_falha")
        self.horizontalLayout_11.addWidget(self.exibir_tempo_p_falha)
        spacerItem16 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem16)
        self.verticalLayout_11.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem17)
        self.calcular_tempo_p_falha = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        self.calcular_tempo_p_falha.setObjectName("calcular_tempo_p_falha")
        self.horizontalLayout_12.addWidget(self.calcular_tempo_p_falha)
        spacerItem18 = QtWidgets.QSpacerItem(35, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem18)
        self.verticalLayout_11.addLayout(self.horizontalLayout_12)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(-10, 0, 531, 731))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem19 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem19)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(0, 0))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.link_to_opp = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.link_to_opp.sizePolicy().hasHeightForWidth())
        self.link_to_opp.setSizePolicy(sizePolicy)
        self.link_to_opp.setStyleSheet("border-image: url(:/icons/icons/link_to_page.png);")
        self.link_to_opp.setText("")
        self.link_to_opp.setObjectName("link_to_opp")
        self.horizontalLayout_2.addWidget(self.link_to_opp)
        spacerItem20 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem20)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.conf_min = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.conf_min.setFont(font)
        self.conf_min.setAlignment(QtCore.Qt.AlignCenter)
        self.conf_min.setObjectName("conf_min")
        self.verticalLayout.addWidget(self.conf_min)
        self.dispo_min = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.dispo_min.setFont(font)
        self.dispo_min.setAlignment(QtCore.Qt.AlignCenter)
        self.dispo_min.setObjectName("dispo_min")
        self.verticalLayout.addWidget(self.dispo_min)
        spacerItem21 = QtWidgets.QSpacerItem(20, 4, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem21)
        self.line_sup = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.line_sup.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_sup.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_sup.setObjectName("line_sup")
        self.verticalLayout.addWidget(self.line_sup)
        spacerItem22 = QtWidgets.QSpacerItem(20, 4, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem22)
        self.c_reparo_prog = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.c_reparo_prog.setFont(font)
        self.c_reparo_prog.setAlignment(QtCore.Qt.AlignCenter)
        self.c_reparo_prog.setObjectName("c_reparo_prog")
        self.verticalLayout.addWidget(self.c_reparo_prog)
        self.c_reparo_n_prog = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.c_reparo_n_prog.setFont(font)
        self.c_reparo_n_prog.setAlignment(QtCore.Qt.AlignCenter)
        self.c_reparo_n_prog.setObjectName("c_reparo_n_prog")
        self.verticalLayout.addWidget(self.c_reparo_n_prog)
        self.perda = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.perda.setFont(font)
        self.perda.setAlignment(QtCore.Qt.AlignCenter)
        self.perda.setObjectName("perda")
        self.verticalLayout.addWidget(self.perda)
        spacerItem23 = QtWidgets.QSpacerItem(20, 4, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem23)
        self.line_meio = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.line_meio.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_meio.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_meio.setObjectName("line_meio")
        self.verticalLayout.addWidget(self.line_meio)
        spacerItem24 = QtWidgets.QSpacerItem(20, 4, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem24)
        self.t_reparo_prog = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.t_reparo_prog.setFont(font)
        self.t_reparo_prog.setAlignment(QtCore.Qt.AlignCenter)
        self.t_reparo_prog.setObjectName("t_reparo_prog")
        self.verticalLayout.addWidget(self.t_reparo_prog)
        self.disponibilidade_m = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.disponibilidade_m.setFont(font)
        self.disponibilidade_m.setAlignment(QtCore.Qt.AlignCenter)
        self.disponibilidade_m.setObjectName("disponibilidade_m")
        self.verticalLayout.addWidget(self.disponibilidade_m)
        self.tempo_de_servico = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tempo_de_servico.setFont(font)
        self.tempo_de_servico.setAlignment(QtCore.Qt.AlignCenter)
        self.tempo_de_servico.setObjectName("tempo_de_servico")
        self.verticalLayout.addWidget(self.tempo_de_servico)
        spacerItem25 = QtWidgets.QSpacerItem(20, 4, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem25)
        self.line_inf = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.line_inf.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_inf.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_inf.setObjectName("line_inf")
        self.verticalLayout.addWidget(self.line_inf)
        spacerItem26 = QtWidgets.QSpacerItem(20, 4, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem26)
        self.pso_w = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pso_w.setFont(font)
        self.pso_w.setAlignment(QtCore.Qt.AlignCenter)
        self.pso_w.setObjectName("pso_w")
        self.verticalLayout.addWidget(self.pso_w)
        self.pso_c1 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pso_c1.setFont(font)
        self.pso_c1.setAlignment(QtCore.Qt.AlignCenter)
        self.pso_c1.setObjectName("pso_c1")
        self.verticalLayout.addWidget(self.pso_c1)
        self.pso_c2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pso_c2.setFont(font)
        self.pso_c2.setAlignment(QtCore.Qt.AlignCenter)
        self.pso_c2.setObjectName("pso_c2")
        self.verticalLayout.addWidget(self.pso_c2)
        self.pso_w_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pso_w_2.setFont(font)
        self.pso_w_2.setAlignment(QtCore.Qt.AlignCenter)
        self.pso_w_2.setObjectName("pso_w_2")
        self.verticalLayout.addWidget(self.pso_w_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem27 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem27)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.conf_lim = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.conf_lim.setMinimumSize(QtCore.QSize(115, 25))
        self.conf_lim.setMaximumSize(QtCore.QSize(115, 25))
        self.conf_lim.setAlignment(QtCore.Qt.AlignCenter)
        self.conf_lim.setClearButtonEnabled(True)
        self.conf_lim.setObjectName("conf_lim")
        self.verticalLayout_2.addWidget(self.conf_lim)
        self.disp_lim = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.disp_lim.setMinimumSize(QtCore.QSize(0, 25))
        self.disp_lim.setMaximumSize(QtCore.QSize(115, 25))
        self.disp_lim.setAlignment(QtCore.Qt.AlignCenter)
        self.disp_lim.setClearButtonEnabled(True)
        self.disp_lim.setObjectName("disp_lim")
        self.verticalLayout_2.addWidget(self.disp_lim)
        spacerItem28 = QtWidgets.QSpacerItem(18, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem28)
        self.c_rep_prog = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.c_rep_prog.setMinimumSize(QtCore.QSize(0, 25))
        self.c_rep_prog.setMaximumSize(QtCore.QSize(115, 25))
        self.c_rep_prog.setAlignment(QtCore.Qt.AlignCenter)
        self.c_rep_prog.setClearButtonEnabled(True)
        self.c_rep_prog.setObjectName("c_rep_prog")
        self.verticalLayout_2.addWidget(self.c_rep_prog)
        self.c_rep_n_prog = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.c_rep_n_prog.setMinimumSize(QtCore.QSize(0, 25))
        self.c_rep_n_prog.setMaximumSize(QtCore.QSize(115, 25))
        self.c_rep_n_prog.setAlignment(QtCore.Qt.AlignCenter)
        self.c_rep_n_prog.setClearButtonEnabled(True)
        self.c_rep_n_prog.setObjectName("c_rep_n_prog")
        self.verticalLayout_2.addWidget(self.c_rep_n_prog)
        self.perdas_parada = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.perdas_parada.setMinimumSize(QtCore.QSize(0, 25))
        self.perdas_parada.setMaximumSize(QtCore.QSize(115, 25))
        self.perdas_parada.setAlignment(QtCore.Qt.AlignCenter)
        self.perdas_parada.setClearButtonEnabled(True)
        self.perdas_parada.setObjectName("perdas_parada")
        self.verticalLayout_2.addWidget(self.perdas_parada)
        spacerItem29 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem29)
        self.t_rep_prog = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.t_rep_prog.setMinimumSize(QtCore.QSize(0, 25))
        self.t_rep_prog.setMaximumSize(QtCore.QSize(115, 25))
        self.t_rep_prog.setAlignment(QtCore.Qt.AlignCenter)
        self.t_rep_prog.setClearButtonEnabled(True)
        self.t_rep_prog.setObjectName("t_rep_prog")
        self.verticalLayout_2.addWidget(self.t_rep_prog)
        self.t_rep_n_prog = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.t_rep_n_prog.setMinimumSize(QtCore.QSize(0, 25))
        self.t_rep_n_prog.setMaximumSize(QtCore.QSize(115, 25))
        self.t_rep_n_prog.setAlignment(QtCore.Qt.AlignCenter)
        self.t_rep_n_prog.setClearButtonEnabled(True)
        self.t_rep_n_prog.setObjectName("t_rep_n_prog")
        self.verticalLayout_2.addWidget(self.t_rep_n_prog)
        self.tempo_servico = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.tempo_servico.setMinimumSize(QtCore.QSize(0, 25))
        self.tempo_servico.setMaximumSize(QtCore.QSize(115, 25))
        self.tempo_servico.setAlignment(QtCore.Qt.AlignCenter)
        self.tempo_servico.setClearButtonEnabled(True)
        self.tempo_servico.setObjectName("tempo_servico")
        self.verticalLayout_2.addWidget(self.tempo_servico)
        spacerItem30 = QtWidgets.QSpacerItem(18, 16, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem30)
        self.limite_tempo = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.limite_tempo.setMinimumSize(QtCore.QSize(0, 25))
        self.limite_tempo.setMaximumSize(QtCore.QSize(115, 25))
        self.limite_tempo.setAlignment(QtCore.Qt.AlignCenter)
        self.limite_tempo.setClearButtonEnabled(True)
        self.limite_tempo.setObjectName("limite_tempo")
        self.verticalLayout_2.addWidget(self.limite_tempo)
        self.c1_pso = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.c1_pso.setMinimumSize(QtCore.QSize(0, 25))
        self.c1_pso.setMaximumSize(QtCore.QSize(115, 25))
        self.c1_pso.setAlignment(QtCore.Qt.AlignCenter)
        self.c1_pso.setClearButtonEnabled(True)
        self.c1_pso.setObjectName("c1_pso")
        self.verticalLayout_2.addWidget(self.c1_pso)
        self.c2_pso = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.c2_pso.setMinimumSize(QtCore.QSize(0, 25))
        self.c2_pso.setMaximumSize(QtCore.QSize(115, 25))
        self.c2_pso.setAlignment(QtCore.Qt.AlignCenter)
        self.c2_pso.setClearButtonEnabled(True)
        self.c2_pso.setObjectName("c2_pso")
        self.verticalLayout_2.addWidget(self.c2_pso)
        self.w_pso = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.w_pso.setMinimumSize(QtCore.QSize(0, 25))
        self.w_pso.setMaximumSize(QtCore.QSize(115, 25))
        self.w_pso.setAlignment(QtCore.Qt.AlignCenter)
        self.w_pso.setClearButtonEnabled(True)
        self.w_pso.setObjectName("w_pso")
        self.verticalLayout_2.addWidget(self.w_pso)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem31 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem31)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem32, 2, 0, 1, 1)
        self.mostrar_custo = QtWidgets.QTextBrowser(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mostrar_custo.sizePolicy().hasHeightForWidth())
        self.mostrar_custo.setSizePolicy(sizePolicy)
        self.mostrar_custo.setMinimumSize(QtCore.QSize(0, 25))
        self.mostrar_custo.setMaximumSize(QtCore.QSize(16777215, 17))
        self.mostrar_custo.setObjectName("mostrar_custo")
        self.gridLayout_3.addWidget(self.mostrar_custo, 2, 3, 1, 1)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem33, 2, 4, 1, 1)
        spacerItem34 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem34, 3, 1, 1, 1)
        spacerItem35 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem35, 2, 2, 1, 1)
        spacerItem36 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem36, 0, 1, 1, 1)
        self.custo_total = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.custo_total.sizePolicy().hasHeightForWidth())
        self.custo_total.setSizePolicy(sizePolicy)
        self.custo_total.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.custo_total.setFont(font)
        self.custo_total.setAlignment(QtCore.Qt.AlignCenter)
        self.custo_total.setObjectName("custo_total")
        self.gridLayout_3.addWidget(self.custo_total, 2, 1, 1, 1)
        self.mostrar_intervalo = QtWidgets.QTextBrowser(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mostrar_intervalo.sizePolicy().hasHeightForWidth())
        self.mostrar_intervalo.setSizePolicy(sizePolicy)
        self.mostrar_intervalo.setMinimumSize(QtCore.QSize(0, 25))
        self.mostrar_intervalo.setMaximumSize(QtCore.QSize(16777215, 17))
        self.mostrar_intervalo.setObjectName("mostrar_intervalo")
        self.gridLayout_3.addWidget(self.mostrar_intervalo, 1, 3, 1, 1)
        self.intevlalo_tempo = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intevlalo_tempo.sizePolicy().hasHeightForWidth())
        self.intevlalo_tempo.setSizePolicy(sizePolicy)
        self.intevlalo_tempo.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.intevlalo_tempo.setFont(font)
        self.intevlalo_tempo.setAlignment(QtCore.Qt.AlignCenter)
        self.intevlalo_tempo.setObjectName("intevlalo_tempo")
        self.gridLayout_3.addWidget(self.intevlalo_tempo, 1, 1, 1, 1)
        spacerItem37 = QtWidgets.QSpacerItem(30, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem37, 1, 2, 1, 1)
        spacerItem38 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem38, 1, 0, 1, 1)
        spacerItem39 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem39, 1, 4, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem40 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem40, 0, 4, 1, 1)
        spacerItem41 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem41, 1, 1, 1, 1)
        spacerItem42 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem42, 0, 0, 1, 1)
        spacerItem43 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem43, 0, 2, 1, 1)
        self.plotar_grafico_opp = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.plotar_grafico_opp.setObjectName("plotar_grafico_opp")
        self.gridLayout.addWidget(self.plotar_grafico_opp, 0, 3, 1, 1)
        self.processar_opp = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.processar_opp.setObjectName("processar_opp")
        self.gridLayout.addWidget(self.processar_opp, 0, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(180, 30, 151, 61))
        self.label_18.setStyleSheet("border-image: url(:/icons/icons/ocm_icon_wth.png);")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(-5, 90, 511, 91))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.tab)
        self.label_20.setGeometry(QtCore.QRect(0, 420, 511, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(-10, 210, 521, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem44 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem44)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setMinimumSize(QtCore.QSize(0, 0))
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_13.addWidget(self.label_29)
        self.link_to_github = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.link_to_github.sizePolicy().hasHeightForWidth())
        self.link_to_github.setSizePolicy(sizePolicy)
        self.link_to_github.setMaximumSize(QtCore.QSize(24, 16777215))
        self.link_to_github.setStyleSheet("border-image: url(:/icons/icons/link_to_page.png);")
        self.link_to_github.setText("")
        self.link_to_github.setObjectName("link_to_github")
        self.horizontalLayout_13.addWidget(self.link_to_github)
        spacerItem45 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem45)
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(-10, 280, 521, 41))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem46 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem46)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setMinimumSize(QtCore.QSize(0, 0))
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_14.addWidget(self.label_30)
        self.link_to_ajuda_yt = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.link_to_ajuda_yt.sizePolicy().hasHeightForWidth())
        self.link_to_ajuda_yt.setSizePolicy(sizePolicy)
        self.link_to_ajuda_yt.setMaximumSize(QtCore.QSize(24, 16777215))
        self.link_to_ajuda_yt.setStyleSheet("border-image: url(:/icons/icons/link_to_page.png);")
        self.link_to_ajuda_yt.setText("")
        self.link_to_ajuda_yt.setObjectName("link_to_ajuda_yt")
        self.horizontalLayout_14.addWidget(self.link_to_ajuda_yt)
        spacerItem47 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem47)
        self.layoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.layoutWidget_3.setGeometry(QtCore.QRect(-10, 350, 521, 41))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem48 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem48)
        self.label_31 = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setMinimumSize(QtCore.QSize(0, 0))
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_15.addWidget(self.label_31)
        self.link_to_doc = QtWidgets.QPushButton(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.link_to_doc.sizePolicy().hasHeightForWidth())
        self.link_to_doc.setSizePolicy(sizePolicy)
        self.link_to_doc.setMaximumSize(QtCore.QSize(24, 16777215))
        self.link_to_doc.setStyleSheet("border-image: url(:/icons/icons/link_to_page.png);")
        self.link_to_doc.setText("")
        self.link_to_doc.setObjectName("link_to_doc")
        self.horizontalLayout_15.addWidget(self.link_to_doc)
        spacerItem49 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem49)
        self.layoutWidget_4 = QtWidgets.QWidget(self.tab)
        self.layoutWidget_4.setGeometry(QtCore.QRect(-10, 440, 531, 71))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem50 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem50)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setMinimumSize(QtCore.QSize(0, 0))
        self.label_32.setMaximumSize(QtCore.QSize(239, 16777215))
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_16.addWidget(self.label_32)
        self.link_kort = QtWidgets.QPushButton(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.link_kort.sizePolicy().hasHeightForWidth())
        self.link_kort.setSizePolicy(sizePolicy)
        self.link_kort.setMaximumSize(QtCore.QSize(24, 16777215))
        self.link_kort.setStyleSheet("border-image: url(:/icons/icons/link_to_page.png);")
        self.link_kort.setText("")
        self.link_kort.setObjectName("link_kort")
        self.horizontalLayout_16.addWidget(self.link_kort)
        spacerItem51 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem51)
        self.layoutWidget_5 = QtWidgets.QWidget(self.tab)
        self.layoutWidget_5.setGeometry(QtCore.QRect(0, 540, 521, 71))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem52 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem52)
        self.label_33 = QtWidgets.QLabel(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        self.label_33.setMinimumSize(QtCore.QSize(0, 0))
        self.label_33.setMaximumSize(QtCore.QSize(239, 16777215))
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_17.addWidget(self.label_33)
        spacerItem53 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem53)
        self.layoutWidget_6 = QtWidgets.QWidget(self.tab)
        self.layoutWidget_6.setGeometry(QtCore.QRect(0, 610, 521, 71))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        spacerItem54 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem54)
        self.label_34 = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_34.sizePolicy().hasHeightForWidth())
        self.label_34.setSizePolicy(sizePolicy)
        self.label_34.setMinimumSize(QtCore.QSize(0, 0))
        self.label_34.setMaximumSize(QtCore.QSize(239, 16777215))
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_23.addWidget(self.label_34)
        spacerItem55 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem55)
        self.label_21 = QtWidgets.QLabel(self.tab)
        self.label_21.setGeometry(QtCore.QRect(0, 520, 511, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.tabWidget.addTab(self.tab, "")
        self.horizontalLayout_5.addWidget(self.tabWidget)
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Prévia do aplicativo"))
        self.label_4.setText(_translate("mainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_5.setText(_translate("mainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_2.setText(_translate("mainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_22.setText(_translate("mainWindow", "Entre com os dados aqui:"))
        self.lineEdit.setText(_translate("mainWindow", "Nome do sistema"))
        self.label_23.setText(_translate("mainWindow", "TTF 1"))
        self.label_24.setText(_translate("mainWindow", "TTF 2"))
        self.label_25.setText(_translate("mainWindow", "TTF 3"))
        self.label_26.setText(_translate("mainWindow", "TTF 4"))
        self.label_27.setText(_translate("mainWindow", "TTF 5"))
        self.processar_rede_2.setText(_translate("mainWindow", "Processar"))
        self.salvar_dados_2.setText(_translate("mainWindow", "Salvar"))
        self.carregar_dados_salvos_2.setText(_translate("mainWindow", "Carregar"))
        self.label_17.setText(_translate("mainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_48.setText(_translate("mainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_49.setText(_translate("mainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.select_weibull.setText(_translate("mainWindow", "Weibull"))
        self.select_lognormal.setText(_translate("mainWindow", "Lognormal"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Dados), _translate("mainWindow", " Dados"))
        self.label_6.setText(_translate("mainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Cálculo da confiabilidade</span></p></body></html>"))
        self.label_7.setText(_translate("mainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Cálculo da taxa de falha</span></p></body></html>"))
        self.label_8.setText(_translate("mainWindow", "Tempo"))
        self.label_9.setText(_translate("mainWindow", "Confiabilidade"))
        self.calcular_conf_para_tempo.setText(_translate("mainWindow", "Calcular"))
        self.label_13.setText(_translate("mainWindow", "Confiabilidade"))
        self.label_14.setText(_translate("mainWindow", "Tempo"))
        self.calcular_tempo_p_conf.setText(_translate("mainWindow", "Calcular"))
        self.label_10.setText(_translate("mainWindow", "Tempo"))
        self.label_12.setText(_translate("mainWindow", "Tx de falha"))
        self.calcular_falha_p_tempo.setText(_translate("mainWindow", "Calcular"))
        self.label_15.setText(_translate("mainWindow", "Tx de falha"))
        self.label_16.setText(_translate("mainWindow", "Tempo"))
        self.calcular_tempo_p_falha.setText(_translate("mainWindow", "Calcular"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("mainWindow", "Indicadores"))
        self.label_11.setText(_translate("mainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Powered by </span><span style=\" font-size:16pt; font-style:italic; color:#00aa00;\">Opp!</span></p></body></html>"))
        self.conf_min.setText(_translate("mainWindow", "Confiabilidade mínima aceitavel"))
        self.dispo_min.setText(_translate("mainWindow", "Disponibilidade mínima aceitavel"))
        self.c_reparo_prog.setText(_translate("mainWindow", "Custo estimado por reparo programado"))
        self.c_reparo_n_prog.setText(_translate("mainWindow", "Custo estimado por reparo não programado"))
        self.perda.setText(_translate("mainWindow", "Perdas devido a parada não programada"))
        self.t_reparo_prog.setText(_translate("mainWindow", "Tempo de reparo programado"))
        self.disponibilidade_m.setText(_translate("mainWindow", "Tempo de reparo não programado"))
        self.tempo_de_servico.setText(_translate("mainWindow", "Tempo de vida de serviço esperado"))
        self.pso_w.setText(_translate("mainWindow", "Intervalo máximo a considerar"))
        self.pso_c1.setText(_translate("mainWindow", "PSO - C1"))
        self.pso_c2.setText(_translate("mainWindow", "PSO - C2"))
        self.pso_w_2.setText(_translate("mainWindow", "PSO - W"))
        self.custo_total.setText(_translate("mainWindow", "Custo Total"))
        self.intevlalo_tempo.setText(_translate("mainWindow", "Intervalo recomendado"))
        self.plotar_grafico_opp.setText(_translate("mainWindow", "Plotar gráfico"))
        self.processar_opp.setText(_translate("mainWindow", "Processar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("mainWindow", "Otimização"))
        self.label_19.setText(_translate("mainWindow", "Otimizador do Custo de Manutenção"))
        self.label_20.setText(_translate("mainWindow", "Criado por:"))
        self.label_29.setText(_translate("mainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Página do aplicativo</span></p></body></html>"))
        self.label_30.setText(_translate("mainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Vídeo Tutorial</span></p></body></html>"))
        self.label_31.setText(_translate("mainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Documentação</span></p></body></html>"))
        self.label_32.setText(_translate("mainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Lucas Kort</span></p></body></html>"))
        self.label_33.setText(_translate("mainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Cecilia </span><span style=\" font-family:\'Calibri,sans-serif\'; font-size:14pt;\">Hernández</span></p></body></html>"))
        self.label_34.setText(_translate("mainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Eliane Christo</span></p></body></html>"))
        self.label_21.setText(_translate("mainWindow", "Agradecimento:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("mainWindow", "Sobre"))

import external_media_rc
